### ISSUE TITLE
SPM Unit testing Limitation 

### ISSUE THREAD

**Issue by IslamMamo** [yosshi4486/EmojiPickerViewController#20]
The Unit testing target can't see the package.
@yosshi4486

**Comment by IslamMamo** [comment]
It would be quite amazing if you could build it in Cocoa pod dependency as well!

**Comment by yosshi4486** [comment]
Hello @IslamMamo, thank you for sharing the problem. Would you tell me more details? 
> The Unit testing target can't see the package.

What situation are you facing that problem? I'll try to reproduce the situation!

**Comment by yosshi4486** [comment]
Since this issue has been no move for a long time, I closed this. Thank you for creating the issue.
